import 'package:flutter/material.dart';

class TheoryExample {
  final String sentence;
  final String note;

  const TheoryExample({required this.sentence, required this.note});
}

class GrammarTopic {
  final String id;
  final String title;
  final String shortDescription;
  final String emoji;
  final Color color;
  final String structure;
  final List<String> useCases;
  final List<String> keyRules;
  final List<TheoryExample> examples;
  final List<String> signalWords;

  const GrammarTopic({
    required this.id,
    required this.title,
    required this.shortDescription,
    required this.emoji,
    required this.color,
    required this.structure,
    required this.useCases,
    required this.keyRules,
    required this.examples,
    this.signalWords = const [],
  });
}

const List<GrammarTopic> kGrammarTopics = [
  GrammarTopic(
    id: 'present_simple',
    title: 'Present Simple',
    shortDescription: 'Habits, facts, and general truths',
    emoji: '🔄',
    color: Color(0xFF5C6BC0),
    structure: 'Subject + base verb (+ s/es for he/she/it)',
    useCases: [
      'Habits and routines',
      'Facts and general truths',
      'Scheduled future events',
      'Permanent situations',
    ],
    keyRules: [
      'Add -s or -es for third-person singular (he, she, it): "She works", "He goes"',
      'Use do/does for questions: "Do you play?", "Does he know?"',
      'Use don\'t/doesn\'t for negatives: "I don\'t eat meat", "She doesn\'t drive"',
      'Spelling rules: verbs ending in -o, -ch, -sh, -ss, -x add -es (go→goes, watch→watches)',
    ],
    examples: [
      TheoryExample(sentence: 'I drink coffee every morning.', note: 'Habit'),
      TheoryExample(sentence: 'Water freezes at 0°C.', note: 'Scientific fact'),
      TheoryExample(sentence: 'She teaches English at a university.', note: 'Permanent job'),
      TheoryExample(sentence: 'The flight leaves at 6 AM tomorrow.', note: 'Scheduled event'),
    ],
    signalWords: ['always', 'usually', 'often', 'sometimes', 'never', 'every day', 'every week'],
  ),
  GrammarTopic(
    id: 'present_continuous',
    title: 'Present Continuous',
    shortDescription: 'Actions happening now or temporary situations',
    emoji: '▶️',
    color: Color(0xFF26A69A),
    structure: 'Subject + am/is/are + verb-ing',
    useCases: [
      'Actions happening right now',
      'Temporary situations',
      'Planned future arrangements',
      'Annoying habits (with "always")',
    ],
    keyRules: [
      'am (I), is (he/she/it), are (you/we/they)',
      'Spelling: double final consonant for short vowel verbs (run→running, sit→sitting)',
      'Drop silent -e before -ing (write→writing, make→making)',
      'Stative verbs rarely use continuous: know, want, love, believe, own, seem, understand',
    ],
    examples: [
      TheoryExample(sentence: 'She is reading a book right now.', note: 'Action at this moment'),
      TheoryExample(sentence: 'I\'m staying with my parents this week.', note: 'Temporary situation'),
      TheoryExample(sentence: 'We are meeting the client on Friday.', note: 'Future arrangement'),
      TheoryExample(sentence: 'He is always losing his keys!', note: 'Annoying habit (with always)'),
    ],
    signalWords: ['now', 'at the moment', 'currently', 'right now', 'this week', 'today'],
  ),
  GrammarTopic(
    id: 'past_simple',
    title: 'Past Simple',
    shortDescription: 'Completed actions and past events',
    emoji: '⏮️',
    color: Color(0xFFEF5350),
    structure: 'Subject + past form of verb',
    useCases: [
      'Completed actions at a specific past time',
      'Sequence of past events',
      'Past habits or states',
    ],
    keyRules: [
      'Regular verbs: add -ed (walk→walked, stop→stopped, study→studied)',
      'Irregular verbs must be memorized: go→went, see→saw, have→had, buy→bought',
      'Use "was" (I/he/she/it) and "were" (you/we/they) for the verb "be"',
      'Questions: Did + subject + base verb? "Did you see that?"',
      'Negatives: didn\'t + base verb: "I didn\'t go to school yesterday."',
    ],
    examples: [
      TheoryExample(sentence: 'I visited Paris last summer.', note: 'Completed action'),
      TheoryExample(sentence: 'She woke up, had breakfast, and left.', note: 'Sequence of events'),
      TheoryExample(sentence: 'He played football every day as a child.', note: 'Past habit'),
      TheoryExample(sentence: 'Did you enjoy the concert?', note: 'Question form'),
    ],
    signalWords: ['yesterday', 'last week', 'ago', 'in 2010', 'when I was young'],
  ),
  GrammarTopic(
    id: 'past_continuous',
    title: 'Past Continuous',
    shortDescription: 'Ongoing actions at a past moment',
    emoji: '⏩',
    color: Color(0xFFFF7043),
    structure: 'Subject + was/were + verb-ing',
    useCases: [
      'An action in progress at a specific past time',
      'A longer background action interrupted by a shorter one',
      'Two simultaneous past actions',
      'Setting the scene in a story',
    ],
    keyRules: [
      'was (I, he, she, it) / were (you, we, they)',
      'Often paired with Past Simple for interrupted actions: "I was cooking WHEN the phone rang"',
      'Use "while" for two simultaneous past continuous actions',
      'Same -ing spelling rules as Present Continuous',
    ],
    examples: [
      TheoryExample(sentence: 'At 8 PM, I was watching TV.', note: 'Action in progress at specific time'),
      TheoryExample(sentence: 'I was cooking when the phone rang.', note: 'Interrupted action'),
      TheoryExample(sentence: 'While he was reading, she was cooking.', note: 'Simultaneous actions'),
    ],
    signalWords: ['while', 'when', 'at that moment', 'at 8 PM', 'all day'],
  ),
  GrammarTopic(
    id: 'present_perfect',
    title: 'Present Perfect',
    shortDescription: 'Past actions with present relevance',
    emoji: '✅',
    color: Color(0xFF66BB6A),
    structure: 'Subject + have/has + past participle',
    useCases: [
      'Life experiences (ever/never)',
      'Recent actions with a present result',
      'Actions lasting from past to now (since/for)',
      'Actions that happened at an unspecified time',
    ],
    keyRules: [
      'have (I/you/we/they), has (he/she/it)',
      'Use regular past participle (-ed) or irregular form (go→gone, see→seen, eat→eaten)',
      '"Since" = from a point in time: "since 2020", "since Monday"',
      '"For" = duration: "for 3 years", "for a long time"',
      'Never use with specific finished time expressions (yesterday, last week, in 2010)',
    ],
    examples: [
      TheoryExample(sentence: 'I have visited Japan twice.', note: 'Life experience'),
      TheoryExample(sentence: 'She has lost her phone. (She can\'t find it now)', note: 'Result in present'),
      TheoryExample(sentence: 'We have lived here for ten years.', note: 'Duration up to now'),
      TheoryExample(sentence: 'Have you ever tried sushi?', note: 'Experience question with ever'),
    ],
    signalWords: ['ever', 'never', 'already', 'yet', 'just', 'since', 'for', 'recently', 'lately'],
  ),
  GrammarTopic(
    id: 'past_perfect',
    title: 'Past Perfect',
    shortDescription: 'An action before another past action',
    emoji: '⏪',
    color: Color(0xFFAB47BC),
    structure: 'Subject + had + past participle',
    useCases: [
      'An action that happened before another past action',
      'Showing the order of past events clearly',
      'In reported speech (backshift from Present Perfect)',
      'In third conditional sentences',
    ],
    keyRules: [
      '"Had" is the same for all subjects (I/you/he/she/we/they had)',
      'The Past Perfect action happened EARLIER than the Past Simple action',
      'Use "already", "by the time", "before", "after", "when", "as soon as" as markers',
      'Negative: "hadn\'t + past participle": "I hadn\'t eaten before the meeting."',
    ],
    examples: [
      TheoryExample(sentence: 'She had already left when I arrived.', note: 'Left = earlier; arrived = later'),
      TheoryExample(sentence: 'He had studied French before he moved to Paris.', note: 'Study came before moving'),
      TheoryExample(sentence: 'By the time the film started, we had found our seats.', note: '"By the time" signals earlier action'),
    ],
    signalWords: ['already', 'before', 'after', 'by the time', 'when', 'as soon as', 'never'],
  ),
  GrammarTopic(
    id: 'future_will_going_to',
    title: 'Future: will & going to',
    shortDescription: 'Predictions, plans, and spontaneous decisions',
    emoji: '🔮',
    color: Color(0xFF42A5F5),
    structure: 'will + base verb  /  am/is/are + going to + base verb',
    useCases: [
      'will: spontaneous decisions made at the moment of speaking',
      'will: predictions based on opinion or belief',
      'will: promises, offers, threats',
      'going to: plans made before the moment of speaking',
      'going to: predictions based on present evidence',
    ],
    keyRules: [
      'will is followed by the base verb (no "to"): "I will call you"',
      '"I\'ll" is the contraction of "I will" — very common in speech',
      '"going to" requires the correct form of "be": am/is/are',
      'Key signal: evidence visible NOW → going to. "Look at those clouds — it\'s going to rain."',
    ],
    examples: [
      TheoryExample(sentence: '"The phone is ringing." "I\'ll get it!"', note: 'Spontaneous decision → will'),
      TheoryExample(sentence: 'I think it will be a great party.', note: 'Opinion/prediction → will'),
      TheoryExample(sentence: 'We are going to visit Rome next month.', note: 'Pre-made plan → going to'),
      TheoryExample(sentence: 'Watch out! You\'re going to fall!', note: 'Evidence-based prediction → going to'),
    ],
    signalWords: ['tomorrow', 'next week', 'soon', 'in the future', 'I think', 'probably'],
  ),
  GrammarTopic(
    id: 'zero_first_conditional',
    title: 'Zero & First Conditional',
    shortDescription: 'Real and possible conditions',
    emoji: '1️⃣',
    color: Color(0xFF26C6DA),
    structure: 'Zero: If + present, present  |  First: If + present, will + base',
    useCases: [
      'Zero Conditional: general truths and scientific facts',
      'Zero Conditional: things that always happen in a given situation',
      'First Conditional: real and likely future possibilities',
      'First Conditional: warnings, promises, threats based on real conditions',
    ],
    keyRules: [
      'Zero: both clauses use Present Simple. "If" can often be replaced with "when".',
      'First: the "if" clause uses Present Simple (NOT will); the result clause uses "will".',
      'The "if" clause can come first or second — but use a comma when it comes first.',
      'Other modals can replace "will": can, may, might, should',
    ],
    examples: [
      TheoryExample(sentence: 'If you heat ice, it melts.', note: 'Zero: scientific fact'),
      TheoryExample(sentence: 'If you press that button, the machine stops.', note: 'Zero: always-true result'),
      TheoryExample(sentence: 'If it rains tomorrow, we will cancel the picnic.', note: 'First: possible future'),
      TheoryExample(sentence: 'I will call you if I need help.', note: 'First: "if" clause at end, no comma'),
    ],
    signalWords: ['if', 'when (zero)', 'unless', 'as long as', 'provided that'],
  ),
  GrammarTopic(
    id: 'second_third_conditional',
    title: 'Second & Third Conditional',
    shortDescription: 'Unreal and hypothetical situations',
    emoji: '💭',
    color: Color(0xFFEC407A),
    structure: 'Second: If + past, would + base  |  Third: If + past perf., would have + p.p.',
    useCases: [
      'Second Conditional: hypothetical or imaginary present/future situations',
      'Second Conditional: giving advice with "If I were you..."',
      'Third Conditional: unreal past situations (impossible to change now)',
      'Third Conditional: expressing regret or imagining an alternative past',
    ],
    keyRules: [
      'Second: Use past simple in "if" clause, but "were" (not "was") for all persons: "If I were rich..."',
      'Second: "would + base verb" in the result clause',
      'Third: Use past perfect in "if" clause: "If she had known..."',
      'Third: "would have + past participle" in the result clause',
      'Mixed conditional: If + past perfect + would + base verb (unreal past, present result)',
    ],
    examples: [
      TheoryExample(sentence: 'If I were rich, I would buy a yacht.', note: 'Second: unreal/hypothetical present'),
      TheoryExample(sentence: 'If I were you, I would apologize immediately.', note: 'Second: advice'),
      TheoryExample(sentence: 'If she had studied harder, she would have passed.', note: 'Third: unreal past'),
      TheoryExample(sentence: 'If he had left earlier, he wouldn\'t have missed the train.', note: 'Third: expressing regret'),
    ],
    signalWords: ['if', 'provided that', 'unless', 'even if', 'otherwise'],
  ),
  GrammarTopic(
    id: 'modal_verbs',
    title: 'Modal Verbs',
    shortDescription: 'Ability, permission, obligation, and possibility',
    emoji: '🎛️',
    color: Color(0xFFFF7043),
    structure: 'Subject + modal verb + base verb (no "to")',
    useCases: [
      'Ability: can / could / be able to',
      'Permission: can / could / may',
      'Possibility: may / might / could',
      'Obligation/Necessity: must / have to / need to',
      'Advice/Recommendation: should / ought to / had better',
    ],
    keyRules: [
      'Modal verbs NEVER take -s in third person: "He can swim" (NOT "He cans swim")',
      'Modal verbs are followed by a BASE verb (no "to"): "She must leave"',
      'Exceptions: ought to, have to, used to, need to — these DO use "to"',
      '"Must" = internal obligation (speaker decides). "Have to" = external rule/obligation.',
      '"May/might" = possibility (might is slightly less certain). "Can/could" = informal permission.',
    ],
    examples: [
      TheoryExample(sentence: 'She can speak three languages.', note: 'can = present ability'),
      TheoryExample(sentence: 'You must submit the form by Friday.', note: 'must = strong obligation'),
      TheoryExample(sentence: 'It might rain later — bring an umbrella.', note: 'might = possibility'),
      TheoryExample(sentence: 'You should see a doctor about that.', note: 'should = advice'),
    ],
    signalWords: ['can', 'could', 'may', 'might', 'must', 'should', 'would', 'shall', 'ought to'],
  ),
  GrammarTopic(
    id: 'passive_voice',
    title: 'Passive Voice',
    shortDescription: 'Focus on the action, not the doer',
    emoji: '🔄',
    color: Color(0xFF7E57C2),
    structure: 'Subject + be (conjugated) + past participle (+ by agent)',
    useCases: [
      'The agent (doer) is unknown or unimportant',
      'Formal, academic, or scientific writing',
      'When you want to focus on the action or the object',
      'News reports and official announcements',
    ],
    keyRules: [
      'Only transitive verbs (verbs that take an object) can be made passive',
      'The tense is shown by the form of "be": is/are (present), was/were (past), will be (future)',
      '"By + agent" is only added when the doer is important or surprising',
      'Present Simple: "is/are + p.p." → "The car is washed every week"',
      'Past Simple: "was/were + p.p." → "The window was broken"',
      'Present Perfect: "has/have been + p.p." → "The report has been submitted"',
    ],
    examples: [
      TheoryExample(sentence: 'The Mona Lisa was painted by Leonardo da Vinci.', note: 'Agent important → use "by"'),
      TheoryExample(sentence: 'The bank was robbed last night.', note: 'Agent unknown → no "by"'),
      TheoryExample(sentence: 'English is spoken all over the world.', note: 'Present simple passive'),
      TheoryExample(sentence: 'The new bridge will be completed next year.', note: 'Future passive'),
    ],
    signalWords: ['is/are done', 'was/were done', 'has been done', 'will be done', 'by'],
  ),
  GrammarTopic(
    id: 'articles',
    title: 'Articles: a, an, the',
    shortDescription: 'Specific and non-specific nouns',
    emoji: '📰',
    color: Color(0xFFFFA726),
    structure: 'a/an + singular countable noun  |  the + specific noun',
    useCases: [
      'a/an: first mention of a non-specific noun',
      'a/an: to classify or identify (jobs, nationalities)',
      'the: second mention of a noun already introduced',
      'the: unique or specific things',
      'No article (Ø): plural or uncountable nouns used as generalizations',
    ],
    keyRules: [
      '"a" before consonant sounds, "an" before vowel sounds — based on SOUND, not spelling: "an hour", "a university"',
      'Use "the" when both speaker and listener know which specific thing is meant',
      '"The" with superlatives: "the best", "the most expensive"',
      '"The" with unique nouns: "the sun", "the moon", "the President of France"',
      'No article with plural/uncountable generalizations: "Dogs are friendly", "Love is blind"',
      'No article with most proper nouns: cities, countries, names (exceptions: "the USA", "the Netherlands")',
    ],
    examples: [
      TheoryExample(sentence: 'I saw a dog. The dog was very friendly.', note: 'a = first mention; the = second mention'),
      TheoryExample(sentence: 'She is an engineer. (an + vowel sound)', note: 'an before vowel sound'),
      TheoryExample(sentence: 'I love music. (Ø = uncountable generalization)', note: 'No article for general uncountable'),
      TheoryExample(sentence: 'The Eiffel Tower is in Paris.', note: 'the = unique landmark, Ø = city name'),
    ],
    signalWords: ['a', 'an', 'the', 'some', 'Ø (no article)'],
  ),
  GrammarTopic(
    id: 'prepositions',
    title: 'Prepositions of Time & Place',
    shortDescription: 'In, on, at for time and location',
    emoji: '📍',
    color: Color(0xFF26A69A),
    structure: 'at / on / in + time/place expression',
    useCases: [
      'at: specific times and precise locations',
      'on: days and dates / surfaces',
      'in: months, years, seasons / enclosed spaces',
    ],
    keyRules: [
      'TIME — at: specific clock time (at 5 PM, at noon, at midnight)',
      'TIME — on: days and specific dates (on Monday, on July 4th, on my birthday)',
      'TIME — in: months, years, seasons, parts of the day (in June, in 2025, in summer, in the morning)',
      'PLACE — at: specific point or location (at the bus stop, at home, at school)',
      'PLACE — on: surfaces and floors (on the table, on the wall, on the 3rd floor)',
      'PLACE — in: enclosed spaces, cities, countries (in the room, in London, in France)',
      'Exceptions: at night (NOT in the night); at the weekend (British English)',
    ],
    examples: [
      TheoryExample(sentence: 'Meet me at the café at 3 PM on Friday.', note: 'at = place & time; on = day'),
      TheoryExample(sentence: 'She was born in July in 1995.', note: 'in = month; in = year'),
      TheoryExample(sentence: 'The keys are on the table in the kitchen.', note: 'on = surface; in = enclosed space'),
      TheoryExample(sentence: 'I study best in the morning.', note: 'in = part of the day'),
    ],
    signalWords: ['at', 'on', 'in', 'by', 'until', 'for', 'during', 'since'],
  ),
  GrammarTopic(
    id: 'reported_speech',
    title: 'Reported Speech',
    shortDescription: 'Reporting what someone else said',
    emoji: '💬',
    color: Color(0xFFEF5350),
    structure: 'Subject + reporting verb + (that) + reported clause (with tense shift)',
    useCases: [
      'Reporting statements (say, tell)',
      'Reporting questions (ask, wonder, want to know)',
      'Reporting commands and requests (tell, ask, order, warn)',
    ],
    keyRules: [
      'Tense backshift: Present Simple → Past Simple: "I work" → "She said she worked"',
      'Present Continuous → Past Continuous: "I am going" → "He said he was going"',
      'Past Simple → Past Perfect: "I saw it" → "She said she had seen it"',
      'Will → Would, Can → Could, May → Might',
      'Pronouns change: "I" → "he/she", "you" → "I/they", "my" → "his/her"',
      'Time expressions change: "today" → "that day", "tomorrow" → "the next day", "now" → "then"',
      'Use "tell" with an object: "She told me...". Use "say" without: "She said..."',
    ],
    examples: [
      TheoryExample(sentence: '"I am tired." → She said she was tired.', note: 'Present continuous → Past continuous'),
      TheoryExample(sentence: '"I will help you." → He said he would help me.', note: 'will → would; pronoun change'),
      TheoryExample(sentence: '"Did you finish?" → She asked if I had finished.', note: 'Reported question, no inversion'),
      TheoryExample(sentence: '"Close the door!" → He told me to close the door.', note: 'Command → to + infinitive'),
    ],
    signalWords: ['said', 'told', 'asked', 'replied', 'mentioned', 'claimed', 'that'],
  ),
  GrammarTopic(
    id: 'relative_clauses',
    title: 'Relative Clauses',
    shortDescription: 'Defining and non-defining clauses',
    emoji: '🔗',
    color: Color(0xFF42A5F5),
    structure: 'who/which/that/where/whose + clause',
    useCases: [
      'Defining relative clauses: essential information about a noun',
      'Non-defining relative clauses: extra, non-essential information',
      'Identifying people, things, places, and possession',
    ],
    keyRules: [
      'who = for people, which = for things, that = for people or things (defining only)',
      'where = for places, whose = for possession, when = for times',
      'DEFINING: No commas. The clause is essential to identify the noun.',
      'NON-DEFINING: Use commas. The clause adds extra info but the sentence is still clear without it.',
      'In non-defining clauses: never use "that"; never omit the pronoun',
      'In defining clauses: you can omit the pronoun if it is the OBJECT of the clause',
    ],
    examples: [
      TheoryExample(sentence: 'The man who called you is waiting outside.', note: 'Defining: who = person, essential'),
      TheoryExample(sentence: 'The book (that) I bought is fascinating.', note: 'Defining: "that" is omittable as object'),
      TheoryExample(sentence: 'My sister, who lives in London, is visiting us.', note: 'Non-defining: extra info in commas'),
      TheoryExample(sentence: 'Paris, which is the capital of France, is beautiful.', note: 'Non-defining: use "which", NOT "that"'),
    ],
    signalWords: ['who', 'which', 'that', 'where', 'whose', 'when'],
  ),

  // ── TOEFL / IELTS focused additions ─────────────────────────────────────

  GrammarTopic(
    id: 'subject_verb_agreement',
    title: 'Subject-Verb Agreement',
    shortDescription: 'Making subject and verb agree in number',
    emoji: '⚖️',
    color: Color(0xFF00897B),
    structure: 'Singular subject → singular verb  |  Plural subject → plural verb',
    useCases: [
      'Choosing the correct verb form for a subject',
      'Tricky subjects: collective nouns, indefinite pronouns, compound subjects',
      'Common TOEFL Structure / IELTS Writing error target',
    ],
    keyRules: [
      'Basic rule: add -s/-es for third-person singular: "She works", "He goes"',
      'Indefinite pronouns (everyone, someone, nobody, each, every) take a SINGULAR verb',
      'Compound subjects joined by "and" take a PLURAL verb: "Tom and Lisa are here"',
      'Either...or / Neither...nor: the verb agrees with the NEAREST subject',
      'Collective nouns (team, government, family) take a singular verb in American English',
      'Expressions of time, money, or distance used as a unit take a singular verb: "Five miles is far"',
      'Subjects like "news", "mathematics", "physics" are always singular despite the -s ending',
    ],
    examples: [
      TheoryExample(sentence: 'Everyone in the class is ready.', note: '"Everyone" = singular → "is"'),
      TheoryExample(sentence: 'Neither the teacher nor the students were informed.', note: 'Verb agrees with "students" (nearer subject)'),
      TheoryExample(sentence: 'The committee has made its decision.', note: 'Collective noun = singular in AmE'),
      TheoryExample(sentence: 'Two hours is not enough time.', note: 'Time as a unit = singular'),
    ],
    signalWords: ['each', 'every', 'neither', 'either', 'nobody', 'everyone', 'anyone'],
  ),
  GrammarTopic(
    id: 'gerunds_infinitives',
    title: 'Gerunds & Infinitives',
    shortDescription: 'When to use verb-ing vs to + verb',
    emoji: '🔀',
    color: Color(0xFFE53935),
    structure: 'verb + gerund (verb-ing)  OR  verb + infinitive (to + verb)',
    useCases: [
      'As the object of specific verbs: enjoy, want, decide, avoid…',
      'As the subject of a sentence',
      'After prepositions',
      'In purpose clauses',
    ],
    keyRules: [
      'GERUND-only verbs (enjoy, avoid, finish, mind, consider, suggest, keep, deny, miss, risk)',
      'INFINITIVE-only verbs (want, hope, plan, decide, promise, agree, refuse, offer, expect, need)',
      'BOTH with SAME meaning: like, love, hate, begin, start, continue, prefer',
      'BOTH with DIFFERENT meaning: stop (doing vs. to do), remember, forget, try, regret, mean',
      'After ALL prepositions use a GERUND: "I\'m good at speaking", "before leaving", "instead of going"',
      'Gerunds can act as the subject: "Swimming is healthy"',
    ],
    examples: [
      TheoryExample(sentence: 'I enjoy playing chess. (NOT: I enjoy to play)', note: 'enjoy → gerund only'),
      TheoryExample(sentence: 'She wants to study abroad. (NOT: She wants studying)', note: 'want → infinitive only'),
      TheoryExample(sentence: 'He stopped smoking. (He no longer smokes.)', note: 'stop + gerund = quit the action'),
      TheoryExample(sentence: 'He stopped to smoke. (He paused in order to smoke.)', note: 'stop + infinitive = pause for a purpose'),
    ],
    signalWords: ['enjoy', 'avoid', 'want', 'decide', 'instead of', 'good at', 'before', 'after'],
  ),
  GrammarTopic(
    id: 'perfect_continuous',
    title: 'Perfect Continuous Tenses',
    shortDescription: 'Emphasising duration of ongoing actions',
    emoji: '⏳',
    color: Color(0xFF5E35B1),
    structure:
        'PPC: have/has + been + verb-ing  |  PPastC: had + been + verb-ing',
    useCases: [
      'Present Perfect Continuous: action that started in the past and is still ongoing',
      'Present Perfect Continuous: explaining a present result through a recent prolonged activity',
      'Past Perfect Continuous: action that was ongoing before another past event',
    ],
    keyRules: [
      'Present Perfect Continuous = have/has been + verb-ing: "I have been studying for 3 hours"',
      'Past Perfect Continuous = had been + verb-ing: "She had been waiting for an hour when he arrived"',
      'Use "for" + duration OR "since" + start point with both tenses',
      'PPC vs. Present Perfect Simple: PPC stresses the duration; PP Simple stresses the result',
      'Stative verbs (know, want, love, own) do NOT use continuous forms',
    ],
    examples: [
      TheoryExample(sentence: 'I have been studying English for five years.', note: 'PPC: started in past, still ongoing now'),
      TheoryExample(sentence: 'She looks tired — she has been running.', note: 'PPC: recent activity explains present state'),
      TheoryExample(sentence: 'He had been working there for ten years before he retired.', note: 'PPastC: duration before a past event'),
      TheoryExample(sentence: 'The ground was wet because it had been raining.', note: 'PPastC: explains a past result'),
    ],
    signalWords: ['for', 'since', 'how long', 'all day', 'recently', 'lately'],
  ),
  GrammarTopic(
    id: 'noun_clauses',
    title: 'Noun Clauses',
    shortDescription: 'Clauses that function as nouns',
    emoji: '💡',
    color: Color(0xFF0288D1),
    structure: 'that / if / whether / wh-word + subject + verb',
    useCases: [
      'As the object of verbs of thinking, saying, knowing, believing',
      'As the subject of a sentence',
      'After adjectives: sure, certain, glad, afraid, aware',
      'Embedded (indirect) questions',
    ],
    keyRules: [
      '"That" clause: "I know that she is right." — "that" can often be omitted informally',
      '"If/Whether" clause: used for yes/no embedded questions: "I wonder if he passed"',
      'Wh-word clause: "Tell me where you went." — uses STATEMENT word order (not question order)',
      'CRITICAL: embedded questions DO NOT invert subject/verb: "I don\'t know where he IS" (not "where is he")',
      'Noun clause as subject: "What he said surprised everyone."',
      'After adjectives: "I\'m sure that she will come", "He is aware of what happened"',
    ],
    examples: [
      TheoryExample(sentence: 'I believe (that) she is telling the truth.', note: '"that" = object of "believe"'),
      TheoryExample(sentence: 'Whether he comes or not doesn\'t matter.', note: '"whether" clause as subject'),
      TheoryExample(sentence: 'Can you tell me where the library is?', note: 'Embedded question: statement order, NOT "where is"'),
      TheoryExample(sentence: 'What surprised me was how quickly he learned.', note: 'Two noun clauses: subject and complement'),
    ],
    signalWords: ['that', 'whether', 'if', 'what', 'where', 'when', 'why', 'how', 'who'],
  ),
  GrammarTopic(
    id: 'adverbial_clauses',
    title: 'Adverbial Clauses & Conjunctions',
    shortDescription: 'Clauses expressing time, cause, contrast, and purpose',
    emoji: '🔌',
    color: Color(0xFFFF8F00),
    structure: 'conjunction + subject + verb  (+,)  main clause',
    useCases: [
      'Time clauses: when, while, before, after, until, as soon as, by the time',
      'Cause/Reason: because, since, as, now that',
      'Contrast/Concession: although, even though, while, whereas, despite, in spite of',
      'Purpose: so that, in order to, to + infinitive',
      'Condition: if, unless, as long as, provided that, in case',
    ],
    keyRules: [
      'When the adverbial clause comes FIRST, use a comma: "Although it rained, we went out."',
      'When it comes SECOND, no comma is usually needed: "We went out although it rained."',
      '"Despite" and "in spite of" are PREPOSITIONS — they are followed by a noun/gerund, NOT a clause',
      '"Although/Even though" = full clause; "Despite/In spite of" = noun/gerund phrase',
      'Purpose: use "so that + subject + can/could" OR "in order to + infinitive"',
      '"Unless" = "if not": "Unless you study, you will fail" = "If you don\'t study…"',
    ],
    examples: [
      TheoryExample(sentence: 'Although she was tired, she kept working.', note: 'Contrast + comma (clause first)'),
      TheoryExample(sentence: 'Despite being tired, she kept working.', note: '"Despite" + gerund (NOT a clause)'),
      TheoryExample(sentence: 'I turned off my phone so that I could concentrate.', note: 'Purpose: so that + subject'),
      TheoryExample(sentence: 'As soon as the bell rings, the students leave.', note: 'Time: as soon as = immediately when'),
    ],
    signalWords: ['although', 'because', 'since', 'while', 'unless', 'despite', 'so that', 'as soon as', 'even though'],
  ),
  GrammarTopic(
    id: 'comparison',
    title: 'Comparison: Comparative & Superlative',
    shortDescription: 'Comparing people, things, and ideas',
    emoji: '📊',
    color: Color(0xFF43A047),
    structure:
        'Comparative: adj + -er / more + adj  |  Superlative: the + adj + -est / the most + adj',
    useCases: [
      'Comparing two things (comparative)',
      'Comparing one thing against a group (superlative)',
      'Expressing equality (as…as)',
      'Progressive change (more and more / -er and -er)',
    ],
    keyRules: [
      'Short adjectives (1 syllable): add -er/-est (tall → taller → tallest)',
      'Long adjectives (2+ syllables): use more/most (beautiful → more beautiful → most beautiful)',
      '2-syllable adjectives ending in -y: change y→i and add -er/-est (happy → happier → happiest)',
      'Irregular: good → better → best  |  bad → worse → worst  |  far → farther → farthest',
      'Equality: as + adj + as: "She is as tall as her brother"',
      'Double comparative (parallel increase): "The harder you work, the better the results"',
      'Use "than" after a comparative: "faster than", "more interesting than"',
    ],
    examples: [
      TheoryExample(sentence: 'This exam is harder than the last one.', note: 'Comparative: 1-syllable adj + -er + than'),
      TheoryExample(sentence: 'Tokyo is the most expensive city I have visited.', note: 'Superlative: most + adj'),
      TheoryExample(sentence: 'My score is not as high as yours.', note: 'Negative equality: not as…as'),
      TheoryExample(sentence: 'The more you practice, the more confident you become.', note: 'Double comparative structure'),
    ],
    signalWords: ['than', 'as...as', 'the most', 'the least', 'more', 'less', 'better', 'worse'],
  ),
];

// ── Special topic used for the 40-question mixed quiz ────────────────────
const GrammarTopic kMixedQuizTopic = GrammarTopic(
  id: 'mixed_quiz',
  title: 'Mixed Practice Test',
  shortDescription: 'All topics • 40 questions • TOEFL / IELTS ready',
  emoji: '🏆',
  color: Color(0xFFF57F17),
  structure: 'Covers all 21 grammar topics',
  useCases: [
    'Comprehensive TOEFL / IELTS grammar preparation',
    'Testing knowledge across all topics at once',
    '40 questions with detailed explanations',
  ],
  keyRules: [],
  examples: [],
  signalWords: [],
);
